language: nix

env:
  global:
    - STATE_VERSION=19.09

script:
- >
  nix-shell '<home-manager>' -A install
  -I home-manager=https://github.com/rycee/home-manager/archive/release-$STATE_VERSION.tar.gz
- echo "{ imports = [ ./users/ati-epage.nix ]; home.stateVersion = \"$STATE_VERSION\"; }" > test-home.nix
- >
  home-manager build --show-trace  --dry-run -f test-home.nix
  -I nixpkgs=https://nixos.org/channels/nixos-$STATE_VERSION/nixexprs.tar.xz
  -I unstable=https://nixos.org/channels/nixpkgs-unstable
  -I home-manager=https://github.com/rycee/home-manager/archive/release-$STATE_VERSION.tar.gz
